sudo: false
language: java
jdk:
- oraclejdk8
after_success:
- mvn jacoco:report coveralls:report
env:
  global:
    secure: JiFDUhyKZ6AUelunpsjIHOBpDh9AvfzR9PIBgWX3j3Xtjm5eZCN5FzkSDXwG6bHWxHX6GOc9tTysxMUa/4S4t+NgQaRuw43uQB865A6k9OTgE5VN48WsxOJXBgCd9zCnWmAhvXl2Qd/YBHY2MuR2633zg76ctM6c9iVXoML5lMTVWQCUp0bRt7X4K+53plmAIwQY2q+UPjOiFiQVonv/W4XrlgiHf2F4C3QHJkXmR5gme1VljA0QKiX36cPHkGsdxkSJi/vZow2YMsAxq8Mt1yEqXGDTHJrsLmYXYABNm99fVn25FfmpUGHsIsi0xV7dJQw3K+tU+7GbTeCRemwvL2xz9/nI202D9QbT3XHIMovahTX6H2FGrWIyBbe/Z9j3HtrJHsupFMghb3zzwTwhEnEH5oxXVqgaeMsR4wfNFkfjHLUooFC30YY8UM//VOdWJkkuHtWRQI4w9cm/8WvkyABYyf8sYgcVpXqVYxVIuw/8uFVnbA8vW5d7Jpn80/JuZE/yh8uwE9Wb+qkN0+sr5VRIArs/ZGGvUsJG0/8fusPPBJ3p0tkVybl6kpv5RsHd+OSvDFj1S5KNj74cUO9/+cIj0OtRdeU749foSy8+BIkJYqKvZsdeg3mNqg0geAzplj5UGh8jTkLNZ70BO/PuEmhBj+gTLHykwdc0eCuUSNw=
notifications:
  slack: 
    secure: "RPEyjGByqZZPNcFYtweiNbkF29xF+Z2rROicRtAUPNxtidNpqApeZpCfnvBF+vM8qWpWg1FqZ7XCt7T+nf+1FejFncXqSfkSHjFfkIGr2KSybtV/fVhKp29rSj8SjH3gwmyWrDiyHM1PpklW5zKVnEObP2XBIn/XxAEkm4hj/oPdwputJ7m7v7oabFzU+G0upsSkCP8QYUEJS/2vvyrn6sW+2CNmBubE90ro76BHkhY2oyNQF1FQ3r2tUMW9/AloACyGhEFJFjXzMnRKSLgkyzyauB9/x5KUPvmPvMF1/v11DVUbF6ypzHbtZJ3jrDrYLzFgCqE1ZovSYasWQ1x6smAJwCU1kPjlcJvq0uP8OMP5NEap0fdKnJm0xgcQcFdtPEYJHk3D1SAPzlPv86vedTdrnhvEwdUVMzT3dx63FQR8LOnkefK78jRWo05bJyzmWey6FbVaGG0TGmrWKF+1Ix2/NjXrcqdLgbQ3u3R0y8NNw9OAbtiC/0H2IbXO6sm62eSsiXi2IaKnXBFU0g1JRqKMm9/SPeBPq1pg7iJlpM0gi9MGSW0DXqYPBscP4L7jFB0OfFO8a8/UoClMpM5BzMdFSd3cfeNMDimscIWDKoPWjdSL4XuZWLPi3Abu+p+/JMrOY/0U2wIjLDra7crCYLI8CcNLqLLSl6nObqaXydk="
